openapi: 3.1.0

info:
  title: Prediction Guard API
  description: "This is the Prediction Guard API, designed to provide various language-related services and checks."
  version: "1.2"

servers:
  - url: https://{your-pg.api-domain}.com

paths:
  /chat/completions:
    post:
      summary: Chat Completions
      description: Generate chat completions based on a conversation history.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - model
                - messages
              type: object
              properties:
                model:
                  type: string
                  description: The chat model to use for generating completions.
                messages:
                  oneOf:
                    - type: string
                      description: A string of the message used for generating completions.
                    - type: array
                      description: An array of messages used for generating completions.
                      items:
                        required:
                          - role
                          - content
                        type: object
                        properties:
                          role:
                            type: string
                            description: The role of the sender (user or assistant).
                          content:
                            oneOf:
                              - type: string
                                description: A string of the message content
                              - type: array
                                description: The content of the message, used for file inputs.
                                items:
                                  type: object
                                  properties:
                                    type:
                                      type: string
                                      description: The type of content ('text', 'image_url').
                                    text:
                                      type: string
                                      description: The text to provide.
                                    image_url:
                                      type: object
                                      properties:
                                        url:
                                          type: string
                                          description: The base64 content with this prefix `data:image/jpeg;base64,`
                                        detail:
                                          type: string
                                          description: Specifies the detail level of the image. Defaults to `auto`.
                frequency_penalty:
                  type: number
                  description: A value between -2.0 and 2.0, with positive values increasingly penalizing new tokens based on their frequency so far in order to decrease further occurrences.
                logit_bias:
                  type: object
                  description: Modifies the likelihood of specified tokens appearing in a response.
                  properties:
                    token:
                      type: string
                      description: A string of the chosen token ID. Value is an int from -100 to 100.
                max_completion_tokens:
                  type: integer
                  description: The maximum number of tokens in the generated completion.
                parallel_tool_calls:
                  type: boolean
                  description: Whether to enable parallel function calling during tool use.
                presence_penalty:
                  type: number
                  description: A value between -2.0 and 2.0, with positive values causing a flat reduction of new tokens based on their existing presence so far in order to decrease further occurrences.
                reasoning_effort:
                  type: string
                  description: Constrains effort on reasoning for reasoning models. Currently supported values are `low`, `medium`, and `high`. Reducing reasoning effort can result in faster responses and fewer tokens used on reasoning in a response. Only supported by reasoning models.
                stop:
                  oneOf:
                    - type: string
                      description: A string representing the token to stop generation.
                    - type: array
                      description: An array representing the token to stop generation.
                      items:
                        type: string
                        description: A string representing the token to stop generation.
                stream:
                  type: boolean
                  description: Whether to stream back the model response.
                stream_options:
                  type: object
                  description: Extra parameters used when streaming the response.
                  properties:
                    include_usage:
                      type: boolean
                      description: Whether to include tokens used in the stream response objects.
                temperature:
                  type: number
                  description: The temperature parameter for controlling randomness in completions. Supports a range of 0.0-2.0.
                tool_choice:
                  oneOf:
                    - type: string
                      description: A string representing a tool choice. Options are 'none', 'auto', or 'required'.
                    - type: object
                      description: An object representing the tool to be chosen
                      properties:
                        type:
                          type: string
                          description: The type of tool.
                        function:
                          type: object
                          description: An object containing the name of the function
                          properties:
                            name: string
                tools:
                  type: array
                  description: The content of the tool call.
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        description: The type of tool to call. Only 'function' is currently supported.
                      function:
                        type: object
                        description: The tool information.
                        properties:
                          name:
                            type: string
                            description: The name of the function to be called.
                          description:
                            type: string
                            description: A description of what the function does.
                          parameters:
                            type: object
                            description: The parameters the function accepts, described as a JSON Schema object.
                          strict:
                            type: boolean
                            description: Whether to enable strict schema adherence when generating the function call.
                top_p:
                  type: number
                  description: The diversity of the generated text based on nucleus sampling. Supports a range of 0.0-1.0.
                top_k:
                  type: integer
                  description: The diversity of the generated text based on top-k sampling.
                output:
                  type: object
                  description: Options to affect the output of the response.
                  properties:
                    factuality:
                      type: boolean
                      description: Set to true to turn on factuality processing.
                    toxicity:
                      type: boolean
                      description: Set to true to turn on toxicity processing.
                input:
                  type: object
                  description: Options to affect the input of the request.
                  properties:
                    block_prompt_injection:
                      type: boolean
                      description: Set to true to detect prompt injection attacks.
                    pii:
                      type: string
                      description: Set to either 'block' or 'replace'.
                    pii_replace_method:
                      type: string
                      description: Set to either 'random', 'fake', 'category', 'mask'.
                    entity_list:
                      type: array
                      description: An array of entity types that the PII check should ignore.
                      items:
                        - type: string
                          description: An entity type that the PII check should ignore.
                max_tokens:
                  type: integer
                  description: Deprecated. Please use max_completion_tokens.
            examples:
              Basic:
                value:
                  model: "{{TEXT_MODEL}}"
                  messages:
                    - role: "user"
                      content: "How do you feel about the world in general?"
                  max_completion_tokens: 1000
                  frequency_penalty: 0.1
                  logit_bias:
                    128000: 10
                  parallel_tool_calls: false
                  presence_penalty: 0.1
                  reasoning_effort: "medium"
                  stop: "hello"
                  temperature: 1.0
                  top_p: 1.0
                  top_k: 50
                  output:
                    factuality: true
                    toxicity: true
                  input:
                    pii: "replace"
                    pii_replace_method: "random"
              Streaming:
                value:
                  model: "{{TEXT_MODEL}}"
                  messages:
                    - role: "user"
                      content: "How do you feel about the world in general?"
                  max_completion_tokens: 1000
                  frequency_penalty: 0.1
                  logit_bias:
                    128000: 10
                  parallel_tool_calls: false
                  presence_penalty: 0.1
                  reasoning_effort: "medium"
                  stop: "hello"
                  temperature: 1.0
                  top_p: 1.0
                  top_k: 50
                  stream: true
                  input:
                    pii: "replace"
                    pii_replace_method: "random"
              Image Input:
                value:
                  model: "{{VISION_MODEL}}"
                  messages:
                    - role: "user"
                      content:
                        - type: "text"
                          text: "What is in this image?"
                        - type: "image_url"
                          image_url:
                            url: "data:image/jpeg;base64,<DATA>"
                            detail: "auto"
                  max_completion_tokens: 1000
                  frequency_penalty: 0.1
                  logit_bias:
                    128000: 10
                  parallel_tool_calls: false
                  presence_penalty: 0.1
                  stop: "hello"
                  temperature: 1.0
                  top_p: 1.0
                  top_k: 50
                  output:
                    factuality: true
                    toxicity: true
                  input:
                    pii: "replace"
                    pii_replace_method: "random"
              Function Call:
                value:
                  model: "{{TEXT_MODEL}}"
                  messages:
                    - role: "user"
                      content: "How do you feel about the world in general?"
                  max_completion_tokens: 1000
                  frequency_penalty: 0.1
                  logit_bias:
                    128000: 10
                  parallel_tool_calls: false
                  presence_penalty: 0.1
                  reasoning_effort: "medium"
                  stop: "hello"
                  temperature: 1.0
                  tool_choice:
                    type: "function"
                    function:
                      name: "get_current_weather"
                  tools:
                    - type: "function"
                      function:
                        name: "get_current_weather"
                        description: "Get the current weather in a given location"
                        strict: false
                        parameters:
                          type: "object"
                          properties:
                            location:
                              type: "string"
                              enum:
                                - "celsius"
                                - "fahrenheit"
                          required:
                            - "location"
                  top_p: 1.0
                  top_k: 50
                  output:
                    factuality: true
                    toxicity: true
                  input:
                    pii: "replace"
                    pii_replace_method: "random"
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the chat completion.
                  object:
                    type: string
                    description: Type of object (chat completion).
                  created:
                    type: integer
                    description: Timestamp of when the chat completion was created.
                  model:
                    type: string
                    description: The chat model used for generating completions.
                  choices:
                    type: array
                    description: The set of result choices.
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          description: The index position in the collection.
                        delta:
                          type: object
                          description: The incremental message delta (streaming only).
                          properties:
                            role:
                              type: string
                              description: The role of the sender (user or assistant).
                            content:
                              type: string
                              description: The content of the message.
                        message:
                          type: object
                          description: A result choice.
                          properties:
                            role:
                              type: string
                              description: The role of the sender (user or assistant).
                            content:
                              type: string
                              description: The content of the message.
                            reasoning:
                              type: string
                              description: The reasoning content of the message.
                            tool_calls:
                              type: array
                              description: The tool call function.
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                    description: The autogenerated ID of the function.
                                  type:
                                    type: string
                                    description: The type of tool called.
                                  function:
                                    type: object
                                    description: The tool call function data.
                                    properties:
                                      name:
                                        type: string
                                        description: The name of the function.
                                      arguments:
                                        type: string
                                        description: The function arguments.
                        finish_reason:
                          type: string
                          nullable: true
                          description: The reason the generation finished.
                        generated_text:
                          type: string
                          nullable: true
                          description: The complete generated text.
                  usage:
                    type: object
                    description: The amount of tokens used in the request.
                    properties:
                      prompt_tokens:
                        type: integer
                        description: The amount of tokens included in the request prompt.
                      prompt_tokens_details:
                        type: object
                        description: Further information about the amount of tokens used in the request prompt.
                        properties:
                          audio_tokens:
                            type: integer
                            description: The amount of audio tokens from any input audio files.
                          cached_tokens:
                            type: integer
                            description: The amount of cached tokens used in the request prompt.
                      completion_tokens:
                        type: integer
                        description: The amount of tokens included in the request completion.
                      completion_tokens_details:
                        type: object
                        description: Further information about the amount of tokens in the request completion.
                        properties:
                          reasoning_tokens:
                            type: integer
                            description: The amount of reasoning tokens used by the model.
                          accepted_prediction_tokens:
                            type: integer
                            description: The amount of tokens accepted during the request.
                          rejected_prediction_tokens:
                            type: integer
                            description: The amount of tokens rejected during the request.
                          audio_tokens:
                            type: integer
                            description: The amount of tokens used from output audio files
                      total_tokens:
                        type: integer
                        description: The total amount of tokens used in the entire request.
              examples:
                Basic:
                  value:
                    id: "chat-d079eca8-1d6a-451a-a4ac-b0fea1e11a96"
                    object: "chat.completion"
                    created: 1727890629
                    model: "{{TEXT_MODEL}}"
                    choices:
                      - index: 0
                        message:
                          role: "assistant"
                          content: "I feel that the world in general is a complex and ever-evolving place. It has its fair share of beauty, challenges, and opportunities. There are moments of joy, connection, and growth, as well as pain, conflict, and loss. The world is a reflection of the people who inhabit it, and it's essential to maintain a balance between appreciating its wonders and working towards making it a better place for all. It's a constant journey of learning, adapting, and striving for a more harmonious existence."
                          reasoning: "User is asking about how I feel about the world. This is a simple question. No tool call needed."
                Streaming:
                  description: The final streaming chunk
                  format: sse
                  value:
                    id: "chat-6c8c291f-5a06-46e5-94fa-2b0b1e6444c7"
                    object: "chat.completion.chunk"
                    created: 1727796455
                    model: "{{TEXT_MODEL}}"
                    choices:
                      - index: 0
                        delta: { content: " feel" }
                        generated_text: null
                        finish_reason: "length"
                Image Input:
                  value:
                    id: "chat-554c4c24-a1ea-4c9f-b91c-612bbac34f4e"
                    object: "chat.completion"
                    created: 1727890364
                    model: "{{VISION_MODEL}}"
                    choices:
                      - index: 0
                        message:
                          role: "assistant"
                          content: "No, there is no deer in this picture. The image features a man wearing a hat and glasses, smiling for the camera."
                Function Call:
                  value:
                    id: "chat-d079eca8-1d6a-451a-a4ac-b0fea1e11a96"
                    object: "chat.completion"
                    created: 1727890629
                    model: "{{TEXT_MODEL}}"
                    choices:
                      index: 0
                      message:
                        role: "assistant"
                        content: "I feel that the world in general is a complex and ever-evolving place. It has its fair share of beauty, challenges, and opportunities. There are moments of joy, connection, and growth, as well as pain, conflict, and loss. The world is a reflection of the people who inhabit it, and it's essential to maintain a balance between appreciating its wonders and working towards making it a better place for all. It's a constant journey of learning, adapting, and striving for a more harmonious existence."
                        tool_calls:
                          id: "chatcmpl-tool-d8429654d03945c2b70a4a8d05eb7c6d"
                          type: "function"
                          function:
                            name: "get_current_weather"
                            arguments: "{\n    \"location\": \"celsius\"\n}"
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
  schemas:
