openapi: 3.1.0

info:
  title: Prediction Guard API
  description: "This is the Prediction Guard API, designed to provide various language-related services and checks."
  version: "1.2"

servers:
  - url: https://{your-pg.api-domain}.com

paths:
  /completions:
    post:
      summary: Completions
      description: Retrieve text completions based on the provided input.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - model
                - prompt
              type: object
              properties:
                model:
                  type: string
                  description: The chat model to use for generating completions.
                prompt:
                  oneOf:
                    - type: string
                      description: The prompt to use for generating completions.
                    - type: array
                      description: An array of prompts to use for generating completions.
                      items:
                        type: string
                        description: The prompt to use for generating completions.
                frequency_penalty:
                  type: number
                  description: A value between -2.0 and 2.0, with positive values increasingly penalizing new tokens based on their frequency so far in order to decrease further occurrences.
                logit_bias:
                  type: object
                  description: Modifies the likelihood of specified tokens appearing in a response.
                  properties:
                    token:
                      type: string
                      description: A string of the chosen token ID. Value is an int from -100 to 100.
                max_tokens:
                  type: integer
                  description: The maximum number of tokens in the generated completion.
                presence_penalty:
                  type: number
                  description: A value between -2.0 and 2.0, with positive values causing a flat reduction of new tokens based on their existing presence so far in order to decrease further occurrences.
                stop:
                  oneOf:
                    - type: string
                      description: A string representing the token to stop generation.
                    - type: array
                      description: An array representing the token to stop generation.
                      items:
                        type: string
                        description: A string representing the token to stop generation.
                stream:
                  type: boolean
                  description: Whether to stream back the model response.
                stream_options:
                  type: object
                  description: Extra parameters used when streaming the response.
                  properties:
                    include_usage:
                      type: boolean
                      description: Whether to include tokens used in the stream response objects.
                temperature:
                  type: number
                  description: The temperature parameter for controlling randomness in completions. Supports a range of 0.0-2.0.
                top_p:
                  type: number
                  description: The diversity of the generated text based on nucleus sampling. Supports a range of 0.0-1.0.
                top_k:
                  type: integer
                  description: The diversity of the generated text based on top-k sampling.
                output:
                  type: object
                  description: Options to affect the output of the response.
                  properties:
                    factuality:
                      type: boolean
                      description: Set to true to turn on factuality processing.
                    toxicity:
                      type: boolean
                      description: Set to true to turn on toxicity processing.
                input:
                  type: object
                  description: Options to affect the input of the request.
                  properties:
                    block_prompt_injection:
                      type: boolean
                      description: Set to true to detect prompt injection attacks.
                    pii:
                      type: string
                      description: Set to either 'block' or 'replace'.
                    pii_replace_method:
                      type: string
                      description: Set to either 'random', 'fake', 'category', 'mask'.
                    entity_list:
                      type: array
                      description: An array of entity types that the PII check should ignore.
                      items:
                        - type: string
                          description: An entity type that the PII check should ignore.
            examples:
              Basic:
                value:
                  model: "{{TEXT_MODEL}}"
                  prompt: "Will I lose my hair?"
                  max_tokens: 1000
                  frequency_penalty: 0.1
                  logit_bias:
                    128000: 10
                  presence_penalty: 0.1
                  stop: "hello"
                  temperature: 1.0
                  top_p: 1.0
                  top_k: 50
                  output:
                    factuality: true
                    toxicity: true
                  input:
                    pii: "replace"
                    pii_replace_method: "random"
              Streaming:
                value:
                  model: "{{TEXT_MODEL}}"
                  prompt: "Will I lose my hair?"
                  max_tokens: 1000
                  frequency_penalty: 0.1
                  logit_bias:
                    128000: 10
                  presence_penalty: 0.1
                  stop: "hello"
                  stream: true
                  temperature: 1.0
                  top_p: 1.0
                  top_k: 50
                  output:
                    factuality: true
                    toxicity: true
                  input:
                    pii: "replace"
                    pii_replace_method: "random"
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the completion.
                  object:
                    type: string
                    description: Type of object (completion).
                  created:
                    type: integer
                    description: Timestamp of when the completion was created.
                  model:
                    type: string
                    description: The model used for generating the result.
                  choices:
                    type: array
                    description: The set of result choices.
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          description: The index position in the collection.
                        text:
                          type: string
                          description: The generated text.
              examples:
                Basic:
                  value:
                    id: "cmpl-d20e5639-ed8d-48b2-a403-08fe0fdc7add"
                    object: "text_completion"
                    created: 1727889988
                    model: "{{TEXT_MODEL}}"
                    choices:
                      - index: 0
                        text: "Most people lose some hair every day. It's a natural process called shedding. On average, you can lose 50-100 strands of hair a day. However, if you notice an increase in hair loss or if you are experiencing hair loss in large clumps, then it could be a sign of an underlying condition. Hair loss can be triggered by a number of factors such as stress, illness, hormone imbalance, medication, and genetics.\nIf you're concerned about hair loss, you should consult with a trichologist, a hair and scalp specialist. They can help determine the cause of your hair loss and recommend the appropriate treatment."
                Streaming:
                  description: An example of a single streaming chunk
                  value:
                    id": "cmpl-4b78eda0a81145b495fc13c2b3da2041"
                    object: "text_completion"
                    created: 1750950603
                    model: "{{TEXT_MODEL}}"
                    choices:
                      - index: 0
                        text: " please"
                        finish_reason: null
                        stop_reason: null
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
  schemas:
