openapi: 3.1.0

info:
  title: Prediction Guard API
  description: "This is the Prediction Guard API, designed to provide various language-related services and checks."
  version: "1.2"

servers:
  - url: https://{your-pg.api-domain}.com

paths:
  /factuality:
    post:
      summary: Factuality
      description: Check the factuality of a given text compared to a reference.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - reference
                - text
              type: object
              properties:
                reference:
                  type: string
                  description: The reference text for comparison.
                text:
                  type: string
                  description: The text to be checked for factuality.
            examples:
              Basic:
                value:
                  reference: "The President shall receive in full for his services during the term for which he shall have been elected compensation in the aggregate amount of 400,000 a year, to be paid monthly, and in addition an expense allowance of 50,000 to assist in defraying expenses relating to or resulting from the discharge of his official duties."
                  text: "The president of the united states can take a salary of one million dollars"
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the factuality check.
                  object:
                    type: string
                    description: Type of object (factuality.check).
                  created:
                    type: integer
                    description: Timestamp of when the factuality check was created.
                  checks:
                    type: array
                    description: The set of vectorized data.
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          description: The index position in the collection.
                        score:
                          type: number
                          description: The factuality score.
              examples:
                Basic:
                  value:
                    id: "fact-3262157b-1ff2-4d78-8365-c2dcac56cadd"
                    object: "factuality.check"
                    created: 1727891187
                    checks:
                      - index: 0
                        score: 0.7879657745361328
      security:
        - bearerAuth: []

  /injection:
    post:
      summary: Injection
      description: Injection detects potential prompt injection attacks.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - prompt
                - detect
              type: object
              properties:
                prompt:
                  oneOf:
                    - type: string
                      description: The prompt to check for injection attack.
                    - type: array
                      description: An array of prompts to check for injection attacks.
                      items:
                        type: string
                        description: The prompt to check for injection attack.
                detect:
                  type: boolean
                  description: Whether to detect potential injection attacks.
            examples:
              Basic:
                value:
                  prompt: "A short poem may be a stylistic choice or it may be that you have said what you intended to say in a more concise way."
                  detect: true
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the injection check.
                  object:
                    type: string
                    description: Type of object (injection_check).
                  created:
                    type: integer
                    description: Timestamp of when the injection check was created.
                  checks:
                    type: array
                    description: The set of vectorized data.
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          description: The index position in the collection.
                        probability:
                          type: number
                          description: The probability of a potential injection attack.
                        status:
                          type: string
                          description: The response if this choice was successful.
              examples:
                Basic:
                  value:
                    id: "injection-nYb6vl44Uy6gQQ2pmBYYirGquP8vnDyj"
                    object: "injection_check"
                    created: 1717675539
                    checks:
                      - index: 0
                        probability: 0.5
                        status: "success"
      security:
        - bearerAuth: []

  /PII:
    post:
      summary: PII
      description: Replace personal information such as names, SSNs, and emails in a given text.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - prompt
                - replace
              type: object
              properties:
                prompt:
                  oneOf:
                    - type: string
                      description: The prompt to check for personal information.
                    - type: array
                      description: An array of prompts to check for personal information.
                      items:
                        type: string
                        description: The prompt to check for personal information.
                replace:
                  type: boolean
                  description: Whether to replace personal information.
                replace_method:
                  type: string
                  description: The method to use (random, fake, category, mask).
                entity_list:
                  type: array
                  description: An array of entity types that the PII check should ignore.
                  items:
                    type: string
                    description: An entity type that the PII check should ignore.
            examples:
              replace pii:
                value:
                  prompt: "My email is frodo@predictionguard.com and my number is 954-123-4567."
                  replace: true
                  replace_method: "mask"
              detect pii:
                value:
                  prompt: "My email is frodo@predictionguard.com and my number is 954-123-4567."
                  replace: false
              replace pii with entity list:
                value:
                  prompt: "My email is frodo@predictionguard.com and my number is 954-123-4567."
                  replace: true
                  replace_method: "random"
                  entity_list:
                    - "PHONE_NUMBER"
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the PII check.
                  object:
                    type: string
                    description: Type of object (pii_check).
                  created:
                    type: integer
                    description: Timestamp of when the PII check was created.
                  checks:
                    type: array
                    description: The set of vectorized data.
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          description: The index position in the collection.
                        prompt:
                          type: string
                          description: The prompt that was checked for PII. Only returned if no PII is present.
                        new_prompt:
                          type: string
                          description: The new prompt with the replaced information.
                        pii_type_and_positions:
                          type: array
                          description: An array of PII metadata objects
                          items:
                            type: object
                            properties:
                              start:
                                type: integer
                                description: The starting index of the pii item.
                              end:
                                type: integer
                                description: The ending index of the pii item.
                              type:
                                type: string
                                description: The type of the pii item.
                        status:
                          type: string
                          description: The response if this choice was successful.
              examples:
                replace pii:
                  value:
                    id: "pii-MCZ68Tol2Laj0HgoJtvS5CaSljISkWN1"
                    object: "pii_check"
                    created: 1717675949
                    checks:
                      - index: 0
                        new_prompt: "My email is * and my number is *."
                        status: "success"
                detect pii:
                  value:
                    id: "pii-a62a4c76cde74deb-99b3c65e7366bf45"
                    object: "pii_check"
                    created: 1717675949
                    checks:
                      - index: 0
                        pii_types_and_positions:
                          - start: 12
                            end: 37
                            type: "EMAIL_ADDRESS"
                          - start: 18
                            end: 37
                            type: "URL"
                          - start: 55
                            end: 67
                            type: "PHONE_NUMBER"
                        status: "success"
                replace pii with entity list:
                  value:
                    id: "pii-MCZ68Tol2Laj0HgoJtvS5CaSljISkWN1"
                    object: "pii_check"
                    created: 1717675949
                    checks:
                      - index: 0
                        new_prompt: "My email is * and my number is 954-123-4567."
                        status: "success"
      security:
        - bearerAuth: []

  /toxicity:
    post:
      summary: Toxicity
      description: Check the toxicity of a given text.
      requestBody:
        content:
          application/json:
            schema:
              required:
                - text
              type: object
              properties:
                text:
                  type: string
                  description: The text to check for toxicity.
            examples:
              Basic:
                value:
                  text: "Every flight I have is late and I am very angry. I want to hurt someone."
      responses:
        "403":
          description: Failed auth response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "api understands the request but refuses to authorize it"
        "400":
          description: General error response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Description of the error.
              example:
                error: "required fields are missing"
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: Unique ID for the toxicity check.
                  object:
                    type: string
                    description: Type of object (toxicity.check).
                  created:
                    type: integer
                    description: Timestamp of when the toxicity check was created.
                  checks:
                    type: array
                    description: The set of vectorized data.
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                          description: The index position in the collection.
                        score:
                          type: number
                          description: The toxicity score.
              examples:
                Basic:
                  value:
                    id: "toxi-9ab58681-594a-4efd-b358-1933189ca7bb"
                    object: "toxicity.check"
                    created: 1727891256
                    checks:
                      - index: 0
                        score: 0.7072361707687378
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      in: header
  schemas:
